const http=require('http'),fs=require('fs'),path=require('path'),crypto=require('crypto');
const port=Number(process.env.PORT||3019),root=__dirname,envPath=path.join(root,'.env'),usersPath=path.join(root,'users.json');
const isProd=String(process.env.NODE_ENV||'').toLowerCase()==='production';
const sessions=new Map(),loginAttempts=new Map();
const SESSION_MS=8*60*60*1000,FAIL_WINDOW=15*60*1000,MAX_FAILS=5;
function loadCfg(){let cfg={OPENAI_API_KEY:process.env.OPENAI_API_KEY||'',OPENAI_MODEL:process.env.OPENAI_MODEL||'gpt-5.6-luna'};try{for(const line of fs.readFileSync(envPath,'utf8').split(/\r?\n/)){let m=line.match(/^([^#=]+)=(.*)$/);if(m)cfg[m[1].trim()]=m[2].trim()}}catch{}return cfg}
function saveCfg(key,model){fs.writeFileSync(envPath,`OPENAI_API_KEY=${key}\nOPENAI_MODEL=${model||'gpt-5.6-luna'}\n`,'utf8')}
function loadUsers(){try{return JSON.parse(fs.readFileSync(usersPath,'utf8')).users||[]}catch{return []}}
function saveUsers(users){fs.writeFileSync(usersPath,JSON.stringify({users},null,2),'utf8')}
function hashPassword(password,salt=crypto.randomBytes(16).toString('hex')){return {salt,hash:crypto.scryptSync(password,salt,64).toString('hex')}}
function verifyPassword(password,rec){try{let h=crypto.scryptSync(password,rec.salt,64);let b=Buffer.from(rec.hash,'hex');return h.length===b.length&&crypto.timingSafeEqual(h,b)}catch{return false}}
function bootstrapAdmin(){if(loadUsers().length)return;let u=process.env.ADMIN_USERNAME,p=process.env.ADMIN_PASSWORD;if(u&&p&&p.length>=10){let hp=hashPassword(p);saveUsers([{username:u.trim(),role:'admin',enabled:true,password:hp,createdAt:new Date().toISOString(),lastLogin:null}]);console.log('Admin account bootstrapped from environment variables.')}}bootstrapAdmin();
function securityHeaders(res){res.setHeader('X-Content-Type-Options','nosniff');res.setHeader('X-Frame-Options','DENY');res.setHeader('Referrer-Policy','no-referrer');res.setHeader('Permissions-Policy','camera=(), microphone=(), geolocation=()');res.setHeader('Cross-Origin-Opener-Policy','same-origin');res.setHeader('Content-Security-Policy',"default-src 'self'; style-src 'self' 'unsafe-inline'; script-src 'self' 'unsafe-inline'; connect-src 'self'; img-src 'self' data:; frame-ancestors 'none'; base-uri 'self'; form-action 'self'")}
function json(res,code,obj){securityHeaders(res);res.writeHead(code,{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store'});res.end(JSON.stringify(obj))}
function body(req){return new Promise((ok,bad)=>{let d='';req.on('data',c=>{d+=c;if(d.length>1000000){bad(new Error('Request too large'));req.destroy()}});req.on('end',()=>{try{ok(d?JSON.parse(d):{})}catch(e){bad(e)}});req.on('error',bad)})}
function cookies(req){let out={};for(const p of String(req.headers.cookie||'').split(';')){let i=p.indexOf('=');if(i>0)out[p.slice(0,i).trim()]=decodeURIComponent(p.slice(i+1).trim())}return out}
function getSession(req){let t=cookies(req).portal_session,s=t&&sessions.get(t);if(!s)return null;if(Date.now()>s.expires){sessions.delete(t);return null}s.expires=Date.now()+SESSION_MS;return s}
function setSession(res,user){let token=crypto.randomBytes(32).toString('hex');sessions.set(token,{username:user.username,role:user.role,expires:Date.now()+SESSION_MS});let c=`portal_session=${token}; HttpOnly; SameSite=Lax; Path=/; Max-Age=${Math.floor(SESSION_MS/1000)}`+(isProd?'; Secure':'');res.setHeader('Set-Cookie',c)}
function clearSession(req,res){let t=cookies(req).portal_session;if(t)sessions.delete(t);res.setHeader('Set-Cookie','portal_session=; HttpOnly; SameSite=Lax; Path=/; Max-Age=0'+(isProd?'; Secure':''))}
function clientIp(req){return String(req.headers['x-forwarded-for']||req.socket.remoteAddress||'').split(',')[0].trim()}
function loginBlocked(ip){let a=loginAttempts.get(ip);if(!a)return false;if(Date.now()-a.first>FAIL_WINDOW){loginAttempts.delete(ip);return false}return a.count>=MAX_FAILS}
function failLogin(ip){let now=Date.now(),a=loginAttempts.get(ip);if(!a||now-a.first>FAIL_WINDOW)a={count:0,first:now};a.count++;loginAttempts.set(ip,a)}
function sameOrigin(req){let o=req.headers.origin;if(!o)return true;try{return new URL(o).host===req.headers.host}catch{return false}}
function requireAuth(req,res,role){let s=getSession(req);if(!s){json(res,401,{error:'Authentication required'});return null}if(role&&s.role!==role){json(res,403,{error:'Administrator access required'});return null}return s}
function extractText(j){let out=[];for(const item of(j.output||[])){if(item.type==='message')for(const c of(item.content||[])){if(c.type==='output_text'&&c.text)out.push(c.text)}}return out.join('\n').trim()}
async function askOpenAI(payload,cfg){let hist=Array.isArray(payload.history)?payload.history.slice(-10):[],context=(payload.context||'').slice(0,10000);let messages=hist.map(x=>({role:x.role==='assistant'?'assistant':'user',content:[{type:'input_text',text:String(x.content||'').slice(0,5000)}]}));let user=`Portal page: ${payload.page||'IT Knowledge Base'}\n${context?'CURRENT PORTAL ARTICLE CONTEXT:\n'+context+'\n\n':''}USER QUESTION:\n${payload.message}`;messages.push({role:'user',content:[{type:'input_text',text:user}]});let reqBody={model:cfg.OPENAI_MODEL||'gpt-5.6-luna',instructions:'You are a senior MSP escalation engineer inside a personal IT knowledge-base portal. Give practical, safe, step-by-step troubleshooting. Explain exactly where to click, commands to run, what output to expect, how to interpret pass/fail, and the next action. Separate diagnostic/read-only checks from configuration-changing actions. Warn before disruptive commands. Prefer concise but complete steps. Do not invent product UI paths when uncertain; say what to verify.',input:messages,max_output_tokens:1800};let r=await fetch('https://api.openai.com/v1/responses',{method:'POST',headers:{Authorization:'Bearer '+cfg.OPENAI_API_KEY,'Content-Type':'application/json'},body:JSON.stringify(reqBody)});let j=await r.json();if(!r.ok)throw new Error(j?.error?.message||`OpenAI API error ${r.status}`);return extractText(j)||'No text response was returned.'}
const mime={'.html':'text/html; charset=utf-8','.js':'text/javascript; charset=utf-8','.css':'text/css; charset=utf-8','.json':'application/json; charset=utf-8','.txt':'text/plain; charset=utf-8'};
const authUi=(()=>{try{return fs.readFileSync(path.join(root,'auth-ui.fragment'),'utf8')}catch{return ''}})();
function serveFile(req,res,file,injectAuth=false){fs.readFile(file,(e,d)=>{if(e){res.writeHead(404);return res.end('Not found')}securityHeaders(res);let ext=path.extname(file);res.writeHead(200,{'Content-Type':mime[ext]||'application/octet-stream','Cache-Control':'no-store'});if(injectAuth&&ext==='.html'){let s=d.toString('utf8');s=s.replace('</body>',authUi+'\n</body>');return res.end(s)}res.end(d)})}
http.createServer(async(req,res)=>{try{let u=new URL(req.url,'http://127.0.0.1');let p=u.pathname;
if(p==='/api/auth/status'&&req.method==='GET'){let s=getSession(req);return json(res,200,{authenticated:!!s,setupRequired:loadUsers().length===0,username:s?.username,role:s?.role})}
if(p==='/api/login'&&req.method==='POST'){if(!sameOrigin(req))return json(res,403,{error:'Invalid request origin'});let ip=clientIp(req);if(loginBlocked(ip))return json(res,429,{error:'Too many failed sign-in attempts. Try again after 15 minutes.'});if(loadUsers().length===0)return json(res,503,{error:'Administrator account is not configured yet.'});let b=await body(req),name=String(b.username||'').trim();let users=loadUsers(),user=users.find(x=>x.username.toLowerCase()===name.toLowerCase());if(!user||!user.enabled||!verifyPassword(String(b.password||''),user.password)){failLogin(ip);return json(res,401,{error:'Incorrect username or password.'})}loginAttempts.delete(ip);user.lastLogin=new Date().toISOString();saveUsers(users);setSession(res,user);return json(res,200,{ok:true,redirect:'/'})}
if(p==='/api/logout'&&req.method==='POST'){clearSession(req,res);return json(res,200,{ok:true})}
if(p==='/api/me'&&req.method==='GET'){let s=requireAuth(req,res);if(!s)return;return json(res,200,{username:s.username,role:s.role})}
if(p==='/api/admin/users'&&req.method==='GET'){let s=requireAuth(req,res,'admin');if(!s)return;return json(res,200,{users:loadUsers().map(({password,...u})=>u)})}
if(p==='/api/admin/users'&&req.method==='POST'){if(!sameOrigin(req))return json(res,403,{error:'Invalid request origin'});let s=requireAuth(req,res,'admin');if(!s)return;let b=await body(req),username=String(b.username||'').trim(),password=String(b.password||''),role=b.role==='admin'?'admin':'user';if(!/^[A-Za-z0-9._-]{3,40}$/.test(username))return json(res,400,{error:'Username must be 3-40 characters using letters, numbers, dot, dash or underscore.'});if(password.length<10)return json(res,400,{error:'Password must be at least 10 characters.'});let users=loadUsers();if(users.some(x=>x.username.toLowerCase()===username.toLowerCase()))return json(res,409,{error:'Username already exists.'});users.push({username,role,enabled:true,password:hashPassword(password),createdAt:new Date().toISOString(),lastLogin:null});saveUsers(users);return json(res,200,{message:'User account created.'})}
if(p==='/api/admin/user-status'&&req.method==='POST'){if(!sameOrigin(req))return json(res,403,{error:'Invalid request origin'});let s=requireAuth(req,res,'admin');if(!s)return;let b=await body(req),users=loadUsers(),user=users.find(x=>x.username===b.username);if(!user)return json(res,404,{error:'User not found.'});if(user.username===s.username&&!b.enabled)return json(res,400,{error:'You cannot disable your own signed-in admin account.'});user.enabled=!!b.enabled;saveUsers(users);return json(res,200,{message:`${user.username} ${user.enabled?'enabled':'disabled'}.`})}
if(p==='/api/admin/reset-password'&&req.method==='POST'){if(!sameOrigin(req))return json(res,403,{error:'Invalid request origin'});let s=requireAuth(req,res,'admin');if(!s)return;let b=await body(req),password=String(b.password||'');if(password.length<10)return json(res,400,{error:'Password must be at least 10 characters.'});let users=loadUsers(),user=users.find(x=>x.username===b.username);if(!user)return json(res,404,{error:'User not found.'});user.password=hashPassword(password);saveUsers(users);return json(res,200,{message:'Password reset successfully.'})}
if(p==='/api/status'&&req.method==='GET'){let s=requireAuth(req,res);if(!s)return;let c=loadCfg();return json(res,200,{configured:!!c.OPENAI_API_KEY,model:c.OPENAI_MODEL||'gpt-5.6-luna'})}
if(p==='/api/config'&&req.method==='POST'){if(!sameOrigin(req))return json(res,403,{error:'Invalid request origin'});let s=requireAuth(req,res,'admin');if(!s)return;let b=await body(req);if(!/^sk-/.test(b.key||''))return json(res,400,{error:'That does not look like an OpenAI API key.'});let allowed=['gpt-5.6-luna','gpt-5-nano','gpt-5.6-sol'];let model=allowed.includes(b.model)?b.model:'gpt-5.6-luna';if(b.test){try{await askOpenAI({message:'Reply only with: Connected',history:[],context:'',page:'API setup test'},{OPENAI_API_KEY:b.key,OPENAI_MODEL:model})}catch(e){return json(res,400,{error:e.message})}}saveCfg(b.key,model);return json(res,200,{ok:true,model})}
if(p==='/api/config'&&req.method==='DELETE'){if(!sameOrigin(req))return json(res,403,{error:'Invalid request origin'});let s=requireAuth(req,res,'admin');if(!s)return;try{fs.unlinkSync(envPath)}catch{}return json(res,200,{message:'Saved API key removed.'})}
if(p==='/api/chat'&&req.method==='POST'){if(!sameOrigin(req))return json(res,403,{error:'Invalid request origin'});let s=requireAuth(req,res);if(!s)return;let c=loadCfg();if(!c.OPENAI_API_KEY)return json(res,400,{error:'OpenAI API key is not configured yet.'});let b=await body(req);if(!String(b.message||'').trim())return json(res,400,{error:'Question is empty.'});let answer=await askOpenAI(b,c);return json(res,200,{answer,model:c.OPENAI_MODEL})}
if(p==='/login.html'||p==='/login'){return serveFile(req,res,path.join(root,'login.html'),false)}
let s=getSession(req);if(!s){res.writeHead(302,{Location:'/login.html','Cache-Control':'no-store'});return res.end()}
if(p==='/admin.html'&&s.role!=='admin'){res.writeHead(302,{Location:'/'});return res.end()}
if(p==='/gpt-setup.html'||p==='/agent-setup.html'){if(s.role!=='admin'){res.writeHead(302,{Location:'/ask-agent.html'});return res.end()}}
if(p==='/')p='/index.html';let f=path.normalize(path.join(root,decodeURIComponent(p)));if(!f.startsWith(root))return json(res,403,{error:'Forbidden'});return serveFile(req,res,f,path.extname(f)==='.html')
}catch(e){json(res,500,{error:e.message||'Server error'})}}).listen(port,'0.0.0.0',()=>{console.log(`V19 Secure Edition running at http://localhost:${port}`);if(loadUsers().length===0)console.log('SECURITY SETUP REQUIRED: run setup_admin.bat or set ADMIN_USERNAME / ADMIN_PASSWORD environment variables.')});